In [ ]:
import numpy as pd

In [ ]:
list=[1,2,3]

In [ ]:
pd.array(list)

array([1, 2, 3])

In [ ]:
list1=[[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
pd.array(list1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
pd.zeros(3)

array([0., 0., 0.])

In [ ]:
pd.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
pd.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
pd.arange(0,11,3)

array([0, 3, 6, 9])

In [ ]:
pd.ones(4)

array([1., 1., 1., 1.])

In [ ]:
pd.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
pd.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
pd.linspace(3,8,9)

array([3.   , 3.625, 4.25 , 4.875, 5.5  , 6.125, 6.75 , 7.375, 8.   ])

In [ ]:
pd.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
pd.random.rand(3)

array([0.18582424, 0.88712797, 0.78388767])

In [ ]:
pd.random.rand((3))

array([0.44227606, 0.43982886, 0.00276781])

In [ ]:
pd.random.randint(3)

2

In [ ]:
pd.random.randint((4))

3

In [ ]:
pd.random.randint(1,100)

60

In [ ]:
pd.random.randint(1,100,10)

array([62, 83, 68, 84,  3, 14, 63, 68, 90, 73])

In [ ]:
pd.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr=pd.arange(0,25)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.max()

24

In [ ]:
arr.min()

0

In [ ]:
arr.argmax()

24

In [ ]:
arr.argmin()

0

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(5,5).shape

(5, 5)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr[4]

4

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[1:20]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
arr[1:20]=50

In [ ]:
arr

array([ 0, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)[1:20]

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [20, 21, 22, 23, 24]])

In [ ]:
arr_copy=arr.copy()

In [ ]:
arr_copy

array([ 0, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50, 20, 21, 22, 23, 24])

In [ ]:
arry_2d=pd.array(([5,10,15],[20,25,10],[35,40,45]))

In [ ]:
arry_2d

array([[ 5, 10, 15],
       [20, 25, 10],
       [35, 40, 45]])

In [ ]:
arry_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [ ]:
arry_2d>25

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [ ]:
bool_arr=arry_2d>25

In [ ]:
arry_2d[bool_arr]

array([35, 40, 45])

In [ ]:
a1=pd.arange(0,10)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
a1/0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [ ]:
a1*0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
pd.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
pd.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
pd.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
array=pd.arange(10,50)

In [ ]:
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
array=pd.arange(10,51)

In [ ]:
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
array=pd.arange(10,50,2)

In [ ]:
array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [ ]:
array=pd.arange(10,51,2)

In [ ]:
array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
array=pd.arange(0,9)

In [ ]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
pd.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
pd.random.rand(1)

array([0.09430129])

In [ ]:
pd.random.randn(25)

array([ 0.06595753, -0.46275889,  1.09989562, -1.28982402, -1.453578  ,
       -0.86988968,  0.15119326, -1.9590437 , -0.31903724, -0.19614387,
       -0.29902581, -0.62137677, -0.84669661, -0.99627078,  0.82316853,
        0.30855888, -0.07575149, -0.67814776,  0.90693343,  0.43294917,
        1.03086866,  0.04575568, -1.41944334,  0.71930967,  0.80853935])

In [ ]:
pd.random.randn(5,5)

array([[-2.64502479, -0.50375454, -0.64353156, -1.33883525,  0.40471433],
       [ 1.38833007,  1.11131001,  1.76879266, -0.72898535,  0.17809628],
       [-0.31452686, -1.42252298, -0.00361178,  0.02127833,  1.02373533],
       [-0.94203988,  0.06758405,  1.12318445,  0.38996943, -1.3601253 ],
       [ 0.54475724, -0.32881127, -0.16447002,  0.47988155,  1.20897435]])

In [ ]:
pd.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
ar=pd.arange(1,101)

In [ ]:
ar

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
ar.reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
pd.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
mat=pd.arange(1,26).reshape(5,5)

In [ ]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[3,4]

20

In [ ]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [ ]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat.sum()

325

In [ ]:
mat.std()

7.211102550927978

**SINGLE VALUE DECOMPOSITION**

In [1]:
import numpy as np
from numpy import array
from scipy.linalg import svd
A=array([[1,2],[3,4],[5,6]])
print(A)
U,s,VT=svd(A)
print("\n")
print(U)
print("\n")
print(s)
print("\n")
print(VT)

[[1 2]
 [3 4]
 [5 6]]


[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]


[9.52551809 0.51430058]


[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [2]:
U,s,VT=svd(A,full_matrices=True)
print("\n")
print(U)
print("\n")
print(s)
print("\n")
print(VT)



[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]


[9.52551809 0.51430058]


[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [3]:
U,s,VT=svd(A,full_matrices=False)
print("\n")
print(U)
print("\n")
print(s)
print("\n")
print(VT)



[[-0.2298477   0.88346102]
 [-0.52474482  0.24078249]
 [-0.81964194 -0.40189603]]


[9.52551809 0.51430058]


[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [4]:
from numpy import diag
from numpy import dot
from numpy import zeros
print(A)
print("\n")
# Singular-value decomposition
U,s,VT=svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1])) 
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2]
 [3 4]
 [5 6]]


[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [5]:
import numpy as np
# Creating a matrix A
A =  np.array([[3,4,3],[1,2,3],[4,2,1]])
# performing SVD
U, D, VT = np.linalg.svd(A)
# Checking if we can remake the original matrix using U,D,VT
A_remake=(U @ np.diag(D) @ VT)
print(A_remake)

[[3. 4. 3.]
 [1. 2. 3.]
 [4. 2. 1.]]
